### ISSUE TITLE
Page index

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct-wiki#1]
La navigateur va toujours chercher une page index.html, j'en ai ajouté une dans le repo. Il faudrait une redirection propre vers la page MD principale de la documentation.

**Comment by BastienThoral** [comment]
In the root of the publishing source, create a new file called index.md that contains the content you want to display on the main page of your site.

Tip: If index.html is present, this will be used instead of index.md. If neither index.html nor index.md are present, README.md will be used.

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site#creating-your-site

**Comment by BastienThoral** [comment]
Correction, la page d'index s'appelait Index et non index ... f...ing casse.
